services:
  stargate-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      target: development
    command: ng serve --host 0.0.0.0 --poll 2000 --proxy-config proxy.conf.json
    ports:
      - "4201:4200"
    volumes:
      - ./client:/app:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
