services:
  stargate-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      target: development
    command: npm start
    ports:
      - "4201:4200"
    volumes:
      - ./client:/app:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
